spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/db/application_db
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  servlet:
    context-path: /api
